trigger:
  branches:
    include:
      - test/*
      - master

pr:
  branches:
    include:
      - test/*
      - master

#schedules:
#  - cron: '15 18 * * 1-5'
#    displayName: Smoke build
#    branches:
#      include:
#        - master
#    always: true

pool:
  vmImage: ubuntu-latest

jobs:
  - job: BuildAndTest
    displayName: "Build and test"
    condition: in(variables['Build.Reason'], 'IndividualCI', 'BatchedCI','Manual','PullRequest','ResourceTrigger')
    steps:
      - template: templates/run-tests-steps.yml




